name: Continuous Integration
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          run_install: true

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run tsc

      - name: Test
        run: pnpm run test

      - name: Create / Publish Versions
        uses: changesets/action@master
        with:
          version: pnpm run version
          commit: 'chore: Update Versions'
          title: 'chore: update versions'
          publish: pnpm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
